-- Utfall per bil och månad (importeras från Excel av admin) samt funktion som
-- jämför utfallet mot summerad nattprognos per regnr.

create table if not exists public.monthly_equipage_outcome (
  id bigint generated by default as identity primary key,
  -- Alltid första dagen i månaden, t.ex. 2026-09-01.
  month date not null check (month = date_trunc('month', month)::date),
  -- Normaliserat: versaler utan mellanslag/bindestreck.
  regnr text not null,
  total_revenue numeric not null,
  source_file_name text,
  imported_by uuid,
  imported_at timestamptz not null default now(),
  unique (month, regnr)
);

create index if not exists monthly_equipage_outcome_month_idx
  on public.monthly_equipage_outcome (month);

alter table public.monthly_equipage_outcome enable row level security;

-- Endast admin får läsa. Skrivningar görs via service role (importrouten).
create policy "Admins can read monthly outcome"
  on public.monthly_equipage_outcome
  for select
  to authenticated
  using (public.is_admin(auth.uid()));

-- Ersätter hela månadens utfall i en transaktion, så regnr som tagits bort ur
-- en omimporterad fil inte ligger kvar. p_rows: [{ "regnr": "ABC123", "revenue": 1234.5 }].
create or replace function public.replace_monthly_equipage_outcome(
  p_month date,
  p_rows jsonb,
  p_file_name text,
  p_imported_by uuid
) returns integer
language plpgsql
as $$
declare
  v_month date := date_trunc('month', p_month)::date;
  v_count integer;
begin
  delete from public.monthly_equipage_outcome where month = v_month;

  insert into public.monthly_equipage_outcome
    (month, regnr, total_revenue, source_file_name, imported_by)
  select v_month, r.regnr, r.revenue, p_file_name, p_imported_by
  from jsonb_to_recordset(p_rows) as r(regnr text, revenue numeric);

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

revoke all on function public.replace_monthly_equipage_outcome(date, jsonb, text, uuid)
  from public, anon, authenticated;
grant execute on function public.replace_monthly_equipage_outcome(date, jsonb, text, uuid)
  to service_role;

-- Jämför utfall mot prognos per regnr för en månad. Full outer join så bilar
-- som bara finns på ena sidan också syns. Prognosrader utan regnr ingår inte.
-- Kör som anroparen, så RLS (admin) gäller.
create or replace function public.forecast_vs_outcome(p_month date)
returns table (
  regnr text,
  equipage_name text,
  outcome numeric,
  forecast numeric,
  forecast_days integer
)
language sql
stable
as $$
  with m as (select date_trunc('month', p_month)::date as start_date),
  f as (
    select
      upper(regexp_replace(d.equipage_regnr, '[^A-Za-z0-9]', '', 'g')) as regnr,
      sum(d.total_estimated_revenue) as forecast,
      count(distinct d.forecast_date)::integer as forecast_days,
      (array_agg(d.equipage_name order by d.forecast_date desc))[1] as equipage_name
    from public.daily_equipage_forecast d, m
    where d.equipage_regnr is not null
      and d.forecast_date >= m.start_date
      and d.forecast_date < (m.start_date + interval '1 month')::date
    group by 1
  ),
  o as (
    select x.regnr, x.total_revenue
    from public.monthly_equipage_outcome x, m
    where x.month = m.start_date
  )
  select
    coalesce(f.regnr, o.regnr) as regnr,
    f.equipage_name,
    o.total_revenue as outcome,
    f.forecast,
    f.forecast_days
  from f
  full outer join o on o.regnr = f.regnr
  where coalesce(f.regnr, o.regnr) <> '';
$$;
