-- Tabell för nattliga prognoser per ekipage.
-- Fylls av cron-jobbet /api/cron/daily-forecast (körs 00:00 svensk tid)
-- och läses av Analys-fliken via /api/analytics/forecasts.

create table if not exists public.daily_equipage_forecast (
  id bigint generated by default as identity primary key,
  forecast_date date not null,
  equipage_id integer not null,
  equipage_name text not null,
  total_weight_kg numeric not null default 0,
  total_flm numeric not null default 0,
  total_estimated_revenue numeric not null default 0,
  consignment_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (forecast_date, equipage_id)
);

create index if not exists daily_equipage_forecast_date_idx
  on public.daily_equipage_forecast (forecast_date);

create index if not exists daily_equipage_forecast_name_idx
  on public.daily_equipage_forecast (equipage_name);

alter table public.daily_equipage_forecast enable row level security;

-- Endast admin får läsa prognosdatan (Analys-fliken är admin-only).
-- Skrivningar görs enbart av cron-jobbet via service role, som passerar RLS.
create policy "Admins can read daily forecasts"
  on public.daily_equipage_forecast
  for select
  to authenticated
  using (public.is_admin(auth.uid()));
